# Navigation 导航
nav:
  logo: /image/avatar.webp   # 网站的logo
  display_title: true       # 是否显示网站标题
  fixed: false              # 是否固定状态栏

# Menu 目录
menu:
  首页: / || fas fa-home
  博文 || fa fa-graduation-cap:
    分类: /categories/ || fas fa-folder-open
    标签: /tags/ || fas fa-tags
    归档: /archives/ || fas fa-archive
  生活 || fas fa-star:
    音乐: /music/ || fas fa-music
    旅游: /travel/ || fas fa-globe
  友链: /link/ || fas fa-link
  # 关于: /about/ || fas fa-user-circle

# Code 代码
highlight_theme: darker       # 代码颜色主题
highlight_copy: true          # 是否需要复制键
highlight_lang: true          # 是否展示代码语言  
highlight_shrink: false        # 是否展开代码
highlight_height_limit: 300   # 高度限制，单位px
code_word_wrap: false         # 是否需要自动换行

# Social 社交图标（icon: link || the description || color）
social:
  fas fa-envelope: mailto:1740929297@qq.com || Email || "#0da1e3"
  fas fa-user: https://blog.csdn.net/m0_74766888 || CSDN || '#0da1e3'

# Favicon 网站图标
favicon: /image/avatar.webp

# Avatar 头像
avatar:
  img: /image/avatar.webp
  effect: false

# 是否禁止顶部图片
disable_top_img: false

# 主页封面图片
index_img: /image/wallpaper.webp

# 页面默认的顶部图片
default_top_img: /image/wallpaper.webp

# 归档页顶部图片
archive_img:

# 标签页默认的顶部图片
tag_img:

# 特定标签页的顶部图片（- tag name: xxxxx）
tag_per_img:

# 分类目录页的顶部图片
category_img:

# 特定分类目录的顶部图片（- category name: xxxxx）
category_per_img:

# 文章封面
cover:
  index_enable: true    # 主页是否展示文章封面
  aside_enable: false   # 侧栏是否展示文章封面
  archives_enable: true # 归档是否展示文章封面
  position: left        # 封面展示的位置：left/right/both
  default_cover: \image\cover_default.webp       # 默认封面

# 替换无法显示的图片
error_img:
  flink: /img/friend_404.gif
  post_page: /img/404.jpg

# 错误页面
error_404:
  enable: false
  subtitle: 'Page Not Found'
  background: https://i.loli.net/2020/05/19/aKOcLiyPl2JQdFD.png

# 文章元数据
post_meta:
  page: # 主页
    date_type: created  # 文章日期（created or updated or both）
    date_format: date   # 日期类型（date or relative）
    categories: true    # 是否显示分类
    tags: true         # 是否显示标签
    label: true         # 是否显示摘要
  post: # 文章页
    date_type: created  # 文章日期（created or updated or both）
    date_format: date   # 日期类型（date or relative）
    categories: true    # 是否显示分类
    tags: true         # 是否显示标签
    label: true         # 是否显示摘要

# 主页摘要（1自定义，2自动显示，3自动摘取，false）
index_post_content:
  method: 2   # 上述序号
  length: 200 # 显示字数

# 描点
anchor:
  auto_update: false      # 滚动到页面的不同部分时，URL是否自动改变
  click_to_scroll: false  # 点击页面上的标题时，URL是否自动改变

# 图片的文字描述
photofigcaption: false

# 复制
copy:
  enable: true        # 是否开启复制权限
  copyright:
    enable: true     # 是否开启版权信息添加
    limit_count: 250  # 复制字数限制

# 目录
toc:
  post: true            # 文章是否展示目录
  page: false           # 页面是否展示目录
  number: false         # 是否显示章节数
  expand: false         # 是否展开目录
  style_simple: true    # 侧边栏是否只展示目录
  scroll_percent: false # 是否展示滚动进度百分比
  wrap: false

# 文章的复制权限
post_copyright:
  enable: true
  decode: false
  author_href: https://github.com/dasi0227
  license: CC BY-NC-SA 4.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/

# 打赏
reward:
  enable: false
  text:
  QR_code:
    # - img: /img/wechat.jpg
    #   link:
    #   text: wechat

# 文章编辑
post_edit:
  enable: false
  url:

# 相关文章
related_post:
  enable: true        # 是否开启相关文章
  limit: 6            # 相关文章数目 
  date_type: created  # 创建或更新（created or updated）


# 文章过期
noticeOutdate:
  enable: false     # 是否开启文章过期提醒
  style: flat       # 样式（flat or simple）
  limit_day: 500    # 期限
  position: top     # 位置
  message_prev: It has been
  message_next: days since the last update, the content of the article may be outdated.

# 分页（1越新越靠前，2越旧越靠前，false不分页）
post_pagination: 1

# 页脚
footer:
  owner:
    enable: true  # 是否开启页脚
    since: 2023   # 站点建立时间
  custom_text: <p><a style="margin-inline:5px"target="_blank" href="https://hexo.io/">
               <img src="https://img.shields.io/badge/Frame-Hexo-blue?style=flat&logo=hexo" title="博客框架为 Hexo" alt="HEXO"></a>
               <a style="margin-inline:5px"target="_blank" href="https://butterfly.js.org/">
               <img src="https://img.shields.io/badge/Theme-Butterfly-6513df?style=flat&logo=bitdefender" title="主题采用 Butterfly" alt="Butterfly"></a>
               <a style="margin-inline:5px"target="_blank" href="https://github.com/">
               <img src="https://img.shields.io/badge/Source-Github-d021d6?style=flat&logo=GitHub" title="本站项目由 GitHub 托管" alt="GitHub"></a></p>
  copyright: false # Copyright of theme and framework

# 侧边栏
aside:
  enable: true    # 是否开启侧边栏
  hide: false     # 是否隐层侧边栏
  button: false   # 是否需要侧边栏按钮
  mobile: false    # display on mobile
  position: right # 侧边栏位置
  display:
    archive: false
    tag: false
    category: false
  card_author:
    enable: true
    description:
    button:
      enable: true
      icon: fab fa-github
      text: Follow Me
      link: https://github.com/dasi0227
  card_announcement:
    enable: true
    content: 欢迎来到 Dasi's Blog，致力于分享学习笔记，由于部署在国外服务器，需要科学上网以提升访问速度。
  card_recent_post:
    enable: false
    limit: 8        # if set 0 will show all
    sort: date      # date or updated
    sort_order:     # Don't modify the setting unless you know how it works
  card_categories:
    enable: true
    limit: 0        # if set 0 will show all
    expand: none    # none/true/false
    sort_order:     # Don't modify the setting unless you know how it works
  card_tags:
    enable: true
    limit: 0        # if set 0 will show all
    color: false
    orderby: random # Order of tags, random/name/length
    order: 1        # Sort of order. 1, asc for ascending; -1, desc for descending
    sort_order:     # Don't modify the setting unless you know how it works
  card_archives:
    enable: false
    type: monthly     # yearly or monthly
    format: MMMM YYYY # eg: YYYY年MM月
    order: -1         # Sort of order. 1, asc for ascending; -1, desc for descending
    limit: 8          # if set 0 will show all
    sort_order:       # Don't modify the setting unless you know how it works
  card_webinfo:
    enable: true
    post_count: true
    last_push_date: false
    sort_order:       # Don't modify the setting unless you know how it works
  card_post_series:
    enable: true
    series_title: false # The title shows the series name
    orderBy: 'date'     # Order by title or date
    order: -1           # Sort of order. 1, asc for ascending; -1, desc for descending

# 访问人数
busuanzi:
  site_uv: true
  site_pv: true
  page_pv: true

# 运行时间
runtimeshow:
  enable: true
  publish_date: 2024/8/13 00:00:00

# 最新评论
newest_comments:
  enable: false
  sort_order:   # Don't modify the setting unless you know how it works
  limit: 6      # 显示评论数目
  storage: 10   # 缓存时间（min）
  avatar: true  # 是否显示头像

# 右下角按鈕
# 简繁转换
translate:
  enable: false
  default: 繁         # 按钮默认显示
  defaultEncoding: 2  # 网站默认语言
  translateDelay: 0   # 延迟翻译时间
  msgToTraditionalChinese: "繁"
  msgToSimplifiedChinese: "簡"

# 阅读模式
readmode: true

# 夜间模式
darkmode:
  enable: true
  button: true
  autoChangeMode: false # 是否自动切换夜间模式（1跟随系统，2自定义，false）
  start: 
  end: 

# 滚动百分比
rightside_scroll_percent: false

# 按钮排序（readmode,translate,darkmode,hideAside,toc,chat,comment）
rightside_item_order:
  enable: true
  hide: # readmode,translate,darkmode,hideAside
  show: toc,comment,chat,share,darkmode

# 数学：MathJax
mathjax:
  enable: false
  per_page: false

# 数学：KaTeX
katex:
  enable: true
  per_page: true
  hide_scrollbar: true

# 搜索：Algolia search
algolia_search:
  enable: false
  hits:
    per_page: 6

# 搜索：Local search
local_search:
  enable: true
  preload: true           # 是否预加载
  top_n_per_article: 8    # 匹配结果
  unescape: false         # 是否解码html字符串
  CDN:

# 搜索：Docsearch
docsearch:
  enable: false
  appId:
  apiKey:
  indexName:
  option:

# 分享：Share.js（https://github.com/overtrue/share.js）
sharejs:
  enable: true
  sites: twitter,wechat,qq

# 分享：AddToAny（https://www.addtoany.com/）
addtoany:
  enable: false
  item: facebook,twitter,wechat,sina_weibo,facebook_messenger,email,copy_link

# 评论
comments:
  use:
    #- Twikoo                    # 评论服务商
  text: true             # 是否显示评论服务商名字
  lazyload: true         # 是否惰性加载
  count: false            # 是否在文章顶部显示评论数
  card_post_count: false  # 是否在首页文章卡片显示评论数

# disqus
# https://disqus.com/
disqus:
  shortname:
  apikey: # For newest comments widget

# Alternative Disqus - Render comments with Disqus API
# DisqusJS 評論系統，可以實現在網路審查地區載入 Disqus 評論列表，兼容原版
# https://github.com/SukkaW/DisqusJS
disqusjs:
  shortname:
  apikey:
  option:

# livere (來必力)
# https://www.livere.com/
livere:
  uid:

# gitalk
# https://github.com/gitalk/gitalk
gitalk:
  client_id:
  client_secret:
  repo:
  owner:
  admin:
  option:

# valine
# https://valine.js.org
valine:
  appId: # leancloud application app id
  appKey: # leancloud application app key
  avatar: monsterid # gravatar style https://valine.js.org/#/avatar
  serverURLs: # This configuration is suitable for domestic custom domain name users, overseas version will be automatically detected (no need to manually fill in)
  bg: # valine background
  visitor: false
  option:

# waline - A simple comment system with backend support fork from Valine
# https://waline.js.org/
waline:
  serverURL: # Waline server address url
  bg: # waline background
  pageview: false
  option:

# utterances
# https://utteranc.es/
utterances:
  repo:
  # Issue Mapping: pathname/url/title/og:title
  issue_term: pathname
  # Theme: github-light/github-dark/github-dark-orange/icy-dark/dark-blue/photon-dark
  light_theme: github-light
  dark_theme: photon-dark

# Facebook Comments Plugin
# https://developers.facebook.com/docs/plugins/comments/
facebook_comments:
  app_id:
  user_id: # optional
  pageSize: 10 # The number of comments to show
  order_by: social # social/time/reverse_time
  lang: zh_TW # Language en_US/zh_CN/zh_TW and so on

# Twikoo
# https://github.com/imaegoo/twikoo
twikoo:
  envId: https://twikoo.dasi.net.cn/
  region:
  visitor: false
  option:

# Giscus
# https://giscus.app/
giscus:
  repo:
  repo_id:
  category_id:
  theme:
    light: light
    dark: dark
  option:

# Remark42
# https://remark42.com/docs/configuration/frontend/
remark42:
  host: # Your Host URL
  siteId: # Your Site ID
  option:

# Artalk
# https://artalk.js.org/guide/frontend/config.html
artalk:
  server:
  site:
  visitor: false
  option:

# 在线聊天
# Chat Button [recommend]
# It will create a button in the bottom right corner of website, and hide the origin button
chat_btn: false

# The origin chat button is displayed when scrolling up, and the button is hidden when scrolling down
chat_hide_show: false

# chatra
# https://chatra.io/
chatra:
  enable: false
  id:

# tidio
# https://www.tidio.com/
tidio:
  enable: false
  public_key:

# daovoice
# http://dashboard.daovoice.io/app
daovoice:
  enable: false
  app_id:

# crisp
# https://crisp.chat/en/
crisp:
  enable: false
  website_id:

# messenger
# https://developers.facebook.com/docs/messenger-platform/discovery/facebook-chat-plugin/
messenger:
  enable: false
  pageID:
  lang: zh_TW # Language en_US/zh_CN/zh_TW and so on

# 分析统计：Google Analytics
# https://analytics.google.com/analytics/web/
google_analytics:

# 分析统计：Cloudflare Analytics
# https://www.cloudflare.com/zh-tw/web-analytics/
cloudflare_analytics:

# 分析统计：Microsoft Clarity
# https://clarity.microsoft.com/
microsoft_clarity:

# 广告：Google Adsense
google_adsense:
  enable: false
  auto_ads: true
  js: https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js
  client:
  enable_page_level_ads: true

# 广告：Insert ads manually
# ad:
#   index:
#   aside:
#   post:

# 站长验证
# site_verification:
  # - name: google-site-verification
  #   content: xxxxxx

# 美化效果

# 主体颜色
theme_color:
  enable: true
  main: "#49B1F5"               
  paginator: "#00c4b6"                      # 分页器
  button_hover: "#FF7242"                   # 按钮悬停
  text_selection: "#00c4b6"                 # 文本选择
  link_color: "#99a9bf"                     # 链接
  meta_color: "#858585"                     # 元数据
  hr_color: "#A4D8FA"                       # 水平分割线
  code_foreground: "#F47466"                # 代码前景
  code_background: "rgba(27, 31, 35, .05)"  # 代码背景
  toc_color: "#00c4b6"                      # 目录颜
  blockquote_padding_color: "#49b1f5"       # 引用填充
  blockquote_background_color: "#49b1f5"    # 引用背景
  scrollbar_color: "#49b1f5"                # 滚动条

# 顶部图片
index_site_info_top: # 标题距离顶部距离（默认在中间）
index_top_img_height: # 顶部图片的高度（默认全屏）

# 分类页面和标签页面（index是和主页一样，留空是和归档页一样）
category_ui: index
tag_ui: index

# 文字两侧对齐
text_align_justify: false

# 网站背景（图片url或颜色）
background: 

# 页脚背景（false是默认颜色，图片url，颜色，true是和顶部图片一样）
footer_bg: false

# 为页头和页脚添加黑色半透遮罩
mask:
  header: true
  footer: true

# 右下角按钮距离底部距离
rightside_bottom:

# 开启网页进入效果
enter_transitions: true

# 打字效果
activate_power_mode:
  enable: false
  colorful: false # 冒光特效
  shake: false    # 抖动特效
  mobile: false

# 背景特效：静止彩带
canvas_ribbon:
  enable: false
  size: 150
  alpha: 0.6
  zIndex: -1
  click_to_change: true   # 每次点击改变
  mobile: false

# 背景特效：动态彩带
canvas_fluttering_ribbon:
  enable: false
  mobile: false

# 背景特效：帆布袋
canvas_nest:
  enable: false
  color: '0,0,255' #color of lines, default: '0,0,0'; RGB values: (R,G,B).(note: use ',' to separate.)
  opacity: 0.7 # the opacity of line (0~1), default: 0.5.
  zIndex: -1 # z-index property of the background, default: -1.
  count: 99 # the number of lines, default: 99.
  mobile: false

# 点击特效：烟火
fireworks:
  enable: false
  zIndex: 9999 # -1 or 9999
  mobile: false

# 点击特效：爱心
click_heart:
  enable: false
  mobile: false

# 点击特效：文字
clickShowText:
  enable: true
  text:
    - d
    - a
    - s
    - i
  fontSize: 20px
  random: false   # 是否随机展示
  mobile: false

# 网站默认显示设置：light / dark
display_mode: light

# 美化页面显示
beautify:
  enable: false
  field: post               # site全站生效/post文章生效
  title-prefix-icon:        # 标题图标'\f0c1'
  title-prefix-icon-color:  # 标题图标颜色'#F47466'

# 全局字体
font:
  global-font-size: 15px
  code-font-size:
  font-family:
  code-font-family:

# Blog标题
blog_title_font:
  font_link:
  font-family:

# 水平分割线图标
hr_icon:
  enable: true
  icon: '\f005'

# 主页的副标题
subtitle:
  enable: true
  effect: true    # 打字效果
  startDelay: 300 # time before typing starts in milliseconds
  typeSpeed: 100  # type speed in milliseconds
  backSpeed: 10   # backspacing speed in milliseconds
  # Customize typed.js (配置typed.js)
  # https://github.com/mattboldt/typed.js/#customization
  typed_option:
  source: false
  sub:
    - 別在当你丧气的时候忘了坚定，别在意气风发的时候忘了谦逊
    - 慢节奏的我，错像没钥匙的锁
    - 在来来回回试探中揣摩天长地久，青春期的荷尔蒙让爱情留宿一宿
    - 什么是理想爱情思考了多少个夜，刚毕业的男孩大概也只懂得这些
    - 时间又不会为我赖着不走，干嘛停下来为了选择头疼

# 页面加载动图
preloader:
  enable: true
  # source
  # 1. fullpage-loading
  # 2. pace (see https://codebyzach.github.io/pace/)
  source: 1
  pace_css_url:

# 字数统计
wordcount:
  enable: true
  post_wordcount: true
  min2read: true
  total_wordcount: true

#图片大图模式
medium_zoom: false
fancybox: true

# 标签插件
# --------------------------------------

# series (系列文章)
series:
  enable: true
  orderBy: 'title' # Order by title or date
  order: 1 # Sort of order. 1, asc for ascending; -1, desc for descending
  number: true

# abcjs (樂譜渲染)
# See https://github.com/paulrosen/abcjs
abcjs:
  enable: false
  per_page: true

# mermaid
# see https://github.com/mermaid-js/mermaid
mermaid:
  enable: false
  # built-in themes: default/forest/dark/neutral
  theme:
    light: default
    dark: dark

# Note (Bootstrap Callout)
note:
  # Note tag style values:
  #  - simple    bs-callout old alert style. Default.
  #  - modern    bs-callout new (v2-v3) alert style.
  #  - flat      flat callout style with background, like on Mozilla or StackOverflow.
  #  - disabled  disable all CSS styles import of note tag.
  style: flat
  icons: true
  border_radius: 3
  # Offset lighter of background in % for modern and flat styles (modern: -12 | 12; flat: -18 | 6).
  # Offset also applied to label tag variables. This option can work with disabled note tag.
  light_bg_offset: 0


# Pjax
pjax:
  enable: false
  exclude:
    # - xxxx
    # - xxxx

# Inject the css and script (aplayer/meting)
aplayerInject:
  enable: false
  per_page: true

# 弹窗
snackbar:
  enable: false
  position: bottom-right  # 弹窗位置
  bg_light: '#49b1f5' 
  bg_dark: '#1f1f1f'

# 链接预加载
instantpage: true

# 中英文间自动加空格
pangu:
  enable: true
  field: post # site/post

# Lazyload (圖片懶加載)
# https://github.com/verlok/vanilla-lazyload
lazyload:
  enable: true
  field: site # site/post
  placeholder:
  blur: false

# PWA
# See https://github.com/JLHwung/hexo-offline
# ---------------
# pwa:
#   enable: false
#   manifest: /pwa/manifest.json
#   apple_touch_icon: /pwa/apple-touch-icon.png
#   favicon_32_32: /pwa/32.png
#   favicon_16_16: /pwa/16.png
#   mask_icon: /pwa/safari-pinned-tab.svg

# Open graph meta tags
# https://developers.facebook.com/docs/sharing/webmasters/
Open_Graph_meta:
  enable: true
  option:
    # twitter_card:
    # twitter_image:
    # twitter_id:
    # twitter_site:
    # google_plus:
    # fb_admins:
    # fb_app_id:

# Add the vendor prefixes to ensure compatibility
css_prefix: true

# Inject
# Insert the code to head (before '</head>' tag) and the bottom (before '</body>' tag)
# 插入代码到头部 </head> 之前 和 底部 </body> 之前
inject:
  head:
    - <link rel="stylesheet" href="/css/tag.css?1">
    - <link rel="stylesheet" href="/css/nav.css?1">
    - <link rel="stylesheet" href="/css/homeArticle.css?1">
    - <link rel="stylesheet" href="/css/category.css?1">
    - <link rel="stylesheet" href="/css/cursor.css?1">
    - <link rel="stylesheet" href="/css/background.css?1">
    - <link rel="stylesheet" href="/css/rightmenu.css?1">
    - <link rel="stylesheet" href="/css/copyright.css?1">
    - <link rel="stylesheet" href="/css/archive.css?1">
    - <link rel="stylesheet" href="/css/description.css?1">
    - <link rel="stylesheet" href="/css/post.css?1">
  bottom:
    - <script src="https://cdn.bootcdn.net/ajax/libs/clipboard.js/2.0.11/clipboard.min.js"></script>
    - <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    - <script src="/js/rightmenu.js?1"></script>
    - <script src="https://cdn.bootcss.com/jquery/3.4.1/jquery.min.js"></script>
    - <script src="/js/rightside.js?1"></script>
    - <script src="/js/sitetitle.js?1"></script>
    


# CDN
# Don't modify the following settings unless you know how they work
# 非必要請不要修改
CDN:
  # The CDN provider of internal scripts (主題內部 js 的 cdn 配置)
  # option: local/jsdelivr/unpkg/cdnjs/custom
  # Dev version can only choose. ( dev版的主題只能設置為 local )
  internal_provider: local

  # The CDN provider of third party scripts (第三方 js 的 cdn 配置)
  # option: local/jsdelivr/unpkg/cdnjs/custom
  # when set it to local, you need to install hexo-butterfly-extjs
  third_party_provider: local

  # Add version number to url, true or false
  version: true

  # Custom format
  # For example: https://cdn.staticfile.org/${cdnjs_name}/${version}/${min_cdnjs_file}
  custom_format:

  option:
    # abcjs_basic_js:
    # activate_power_mode:
    # algolia_js:
    # algolia_search:
    # aplayer_css:
    # aplayer_js:
    # artalk_css:
    # artalk_js:
    # blueimp_md5:
    # busuanzi:
    # canvas_fluttering_ribbon:
    # canvas_nest:
    # canvas_ribbon:
    # click_heart:
    # clickShowText:
    # disqusjs:
    # disqusjs_css:
    # docsearch_css:
    # docsearch_js:
    # egjs_infinitegrid:
    # fancybox:
    # fancybox_css:
    # fireworks:
    # fontawesome:
    # gitalk:
    # gitalk_css:
    # giscus:
    # instantpage:
    # instantsearch:
    # katex:
    # katex_copytex:
    # lazyload:
    # local_search:
    # main:
    # main_css:
    # mathjax:
    # medium_zoom:
    # mermaid:
    # meting_js:
    # pangu:
    # prismjs_autoloader:
    # prismjs_js:
    # prismjs_lineNumber_js:
    # pjax:
    # sharejs:
    # sharejs_css:
    # snackbar:
    # snackbar_css:
    # translate:
    # twikoo:
    # typed:
    # utils:
    # valine:
    # waline_css:
    # waline_js: